export const dummyProducts = {
  products: [
    {
      id: 11,
      title: "Wireless Headphones",
      description: "Noise-cancelling over-ear headphones with 30 hours battery life.",
      price: 99,
      discountPercentage: 12.5,
      rating: 4.4,
      stock: 45,
      brand: "SoundPro",
      category: "audio",
      thumbnail: "https://via.placeholder.com/150",
      images: [
        "https://via.placeholder.com/300",
        "https://via.placeholder.com/301",
      ],
    },
    {
      id: 12,
      title: "Smartwatch X200",
      description: "Fitness tracking smartwatch with heart rate and sleep monitor.",
      price: 129,
      discountPercentage: 10,
      rating: 4.1,
      stock: 70,
      brand: "TechTime",
      category: "wearables",
      thumbnail: "https://via.placeholder.com/150",
      images: ["https://via.placeholder.com/302"],
    },
    {
      id: 13,
      title: "Gaming Mouse RGB",
      description: "Ergonomic gaming mouse with customizable RGB lighting.",
      price: 49,
      discountPercentage: 8.5,
      rating: 4.6,
      stock: 100,
      brand: "GameForce",
      category: "accessories",
      thumbnail: "https://via.placeholder.com/150",
      images: ["https://via.placeholder.com/303"],
    },
    {
      id: 14,
      title: "4K Ultra HD Monitor",
      description: "27-inch 4K monitor with HDR and ultra-thin bezels.",
      price: 299,
      discountPercentage: 15,
      rating: 4.5,
      stock: 30,
      brand: "ViewMax",
      category: "electronics",
      thumbnail: "https://via.placeholder.com/150",
      images: ["https://via.placeholder.com/304"],
    },
    {
      id: 15,
      title: "Bluetooth Speaker",
      description: "Portable waterproof speaker with 10-hour playtime.",
      price: 59,
      discountPercentage: 5,
      rating: 4.3,
      stock: 80,
      brand: "BoomBox",
      category: "audio",
      thumbnail: "https://via.placeholder.com/150",
      images: ["https://via.placeholder.com/305"],
    },
    {
      id: 16,
      title: "Mechanical Keyboard",
      description: "RGB mechanical keyboard with blue switches.",
      price: 89,
      discountPercentage: 7.5,
      rating: 4.7,
      stock: 60,
      brand: "KeyZone",
      category: "accessories",
      thumbnail: "https://via.placeholder.com/150",
      images: ["https://via.placeholder.com/306"],
    },
    {
      id: 17,
      title: "Smartphone X",
      description: "6.5-inch AMOLED display with 128GB storage and dual camera.",
      price: 499,
      discountPercentage: 11,
      rating: 4.2,
      stock: 25,
      brand: "NextGen",
      category: "phones",
      thumbnail: "https://via.placeholder.com/150",
      images: ["https://via.placeholder.com/307"],
    },
    {
      id: 18,
      title: "Wireless Charger Pad",
      description: "Fast charging pad compatible with all Qi-enabled devices.",
      price: 39,
      discountPercentage: 6,
      rating: 4.0,
      stock: 90,
      brand: "ChargeIt",
      category: "accessories",
      thumbnail: "https://via.placeholder.com/150",
      images: ["https://via.placeholder.com/308"],
    },
    {
      id: 19,
      title: "Laptop Backpack",
      description: "Water-resistant backpack with USB charging port.",
      price: 69,
      discountPercentage: 9,
      rating: 4.5,
      stock: 50,
      brand: "CarryPro",
      category: "bags",
      thumbnail: "https://via.placeholder.com/150",
      images: ["https://via.placeholder.com/309"],
    },
    {
      id: 20,
      title: "Action Camera",
      description: "4K waterproof action camera with wide-angle lens.",
      price: 159,
      discountPercentage: 13,
      rating: 4.3,
      stock: 40,
      brand: "Adventurix",
      category: "cameras",
      thumbnail: "https://via.placeholder.com/150",
      images: ["https://via.placeholder.com/310"],
    },
  ],
  total: 100,
  skip: 10,
  limit: 10,
};
